#!/usr/bin/perl

# this script solicits information for enrollment


use CGI qw/:standard/;
use DBI;

require "/var/www/html/SPLAT/DB.pl";

print header();

print start_html();

$dbh = DBI->connect("DBI:mysql:$database:$server","$dbuser","$password") || die "can't connect";


if (! $dbh) {
    print h1("No database");
  exit(0);
};



print <<"EOT"
<h1>Splat Web Interface</h1>

All credit belongs to <a href="http://www.qsl.net/kd2bd">John Magliacane KD2BD</a>
for his wonderful "splat!" program.  I encourage you to visit his site
and enjoy his talents! 73 de Bill, W5GFE
<hr>

<h1>Registration</h1>

In order to create a plot or map for a station, the system needs to know
<font color='blue'>where</font> the station is.  This page allows you to
enter the geographic information about any station only one time, and then
just rely on database lookups to provide the data to the splat! program.<br>



You need to know that we will "file" the geographical information
so that it appears on plots generated by other users, as well as by
you.  This will ultimately result in a "ham station" map of the area.<br>


While terrain data is available for most locations on the globe, city and political
    boundary data are available only for North America.<br>

<form method="post" action="enroll.pl">
<table border=3 bgcolor='cyan' cellpadding=5>
<tr><th colspan=2>Station Information</th><th>Registration Type</th></tr>
<tr>
<td align='right'>Callsign:</td><td><input type="text" name="callsign" value="callsign" width=7></td>
</tr>
<tr>
<td align='right'>Longitude as  decimal degrees (eg 96.2351):</td><td><input type="text" name="longitude" value="96.2351"><br>  (negative sign for E)</td>
<td bgcolor='yellow'>
<input type='radio' name='inserttype' value='original' checked="checked"> New Registration<br>
<input type='radio' name='inserttype' value='update'> Update or Correct an Existing Registration<br>
</td>
</tr>

<tr><td align='right'>Latitude as decimal degrees (eg 34.456):</td><td> <input type="text" name="latitude" value="34.456"><br> (negative sign for S)</td>
</tr>
<tr><td align='right'>Antenna Height in feet AGL </td><td><input type="text" name="antenna" value="50.0"></td>
</tr>
<tr><td align='right'>
EOT
    ;


print "State where located (for Political Boundaries) </td><td>","\n";


print "<select name='state'>","\n";
my $tabledata = $dbh->prepare("select name, number from states order by name asc");

$tabledata->execute();
printf("<option value=\'NOSTATE\'>Not in USA</option>\n");

while (@fields = $tabledata->fetchrow_array()) {
    printf("<option value=\'$fields[0]\'>$fields[0]</option>\n");
}

$tabledata->finish();
$dbh->disconnect();

printf("</select>\n");

print <<"EOT1"
</td>
    <td>Region <select name='geography'>
        <option value='North_America' selected='selected'>North America</option>
        <option value='South_America'>South America</option>
        <option value='Eurasia'> Eurasia</option>
        <option value='Islands'>Islands</option>
        <option value='Australia'>Australia</option>
        <option value='Africa'>Africa</option>
        </select>
        </td>
</tr>
</table>

<center>
  <input type="reset" value="Start Over">
  <input type="submit" value="Submit Registration"><br>
</center>
</form>

<hr>
EOT1
    ;

print end_html();
